expose_php=Off
display_errors=Off
log_errors=On
memory_limit=256M
upload_max_filesize=__MAX_UPLOAD_SIZE__K
post_max_size=__MAX_UPLOAD_SIZE__K
max_execution_time=120
opcache.enable=1
opcache.validate_timestamps=0
session.cookie_httponly=1
session.cookie_samesite=Lax
