expose_php=Off
display_errors=Off
log_errors=On
memory_limit=__PHP_MEMORY_LIMIT__
upload_max_filesize=__MAX_UPLOAD_SIZE__
post_max_size=__POST_MAX_SIZE__
max_execution_time=__PHP_MAX_EXECUTION_TIME__
opcache.enable=1
opcache.validate_timestamps=0
session.cookie_httponly=1
session.cookie_samesite=Lax
